CREATE TABLE IF NOT EXISTS `#__garyscookbook` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `catid` int(11) NOT NULL DEFAULT '0',
  `catid2` int(11) DEFAULT '0',
  `catid3` int(11) DEFAULT '0',
  `catid4` int(11) DEFAULT '0',
  `catid5` int(11) DEFAULT '0',
  `imgtitle` text NOT NULL,
  `alias` varchar(255) DEFAULT NULL,
  `imgauthor` varchar(150) DEFAULT NULL,
  `imgtext` text NOT NULL,
  `created` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created_by` int(11) DEFAULT '0',
  `created_by_alias` varchar(255) CHARACTER SET utf8 NOT NULL,
  `modified` datetime NOT NULL,
  `modified_by` int(10) NOT NULL,
  `imgcounter` int(11) NOT NULL DEFAULT '0',
  `imgvotes` int(11) NOT NULL DEFAULT '0',
  `imgvotesum` int(11) NOT NULL DEFAULT '0',
  `used_ips` varchar(15) NOT NULL,
  `published` tinyint(1) NOT NULL DEFAULT '0',
  `default_con` tinyint(1) NOT NULL,
  `access` tinyint(3) DEFAULT '0',
  `imgfilename` varchar(50) DEFAULT '',
  `imgthumbname` varchar(50) DEFAULT '',
  `checked_out` int(11) NOT NULL DEFAULT '0',
  `checked_out_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `doc` tinyint(1) NOT NULL DEFAULT '0',
  `vegan` tinyint(1) NOT NULL DEFAULT '0',
  `price` varchar(20) DEFAULT NULL,
  `country` varchar(50) DEFAULT NULL,
  `portion` varchar(20) DEFAULT NULL,
  `aging` varchar(20) DEFAULT NULL,
  `years` varchar(20) DEFAULT NULL,
  `grapes` text NOT NULL,
  `ingredients` text,
  `properties` text NOT NULL,
  `notes` text,
  `expic1` varchar(200) DEFAULT NULL,
  `expic1_tn` varchar(50) DEFAULT '',
  `expic2` varchar(200) DEFAULT NULL,
  `expic2_tn` varchar(50) DEFAULT '',
  `expic3` varchar(200) DEFAULT NULL,
  `expic3_tn` varchar(50) DEFAULT '',
  `expic4` varchar(200) DEFAULT NULL,
  `expic4_tn` varchar(50) DEFAULT '',
  `laktose` tinyint(1) NOT NULL DEFAULT '0',
  `diaet` tinyint(1) NOT NULL DEFAULT '0',
  `gluten` tinyint(1) NOT NULL DEFAULT '0',
  `amount` varchar(50) DEFAULT '',
  `kcal` varchar(10) DEFAULT '',
  `kjoule` varchar(10) DEFAULT '',
  `fat` varchar(10) DEFAULT '',
  `breadunit` varchar(10) DEFAULT '',
  `protein` varchar(10) DEFAULT '',
  `carbohydrates` varchar(10) DEFAULT '',
  `newdate` varchar(20) DEFAULT NULL,
  `createuser` varchar(150) NOT NULL,
  `createip` varchar(15) NOT NULL DEFAULT '',
  `changed_by` int(11) DEFAULT '0',
  `changeuser` varchar(150) NOT NULL DEFAULT '',
  `changeip` varchar(15) NOT NULL DEFAULT '',
  `ordering` int(10) DEFAULT '0',
  `params` text NOT NULL,
  `metakey` text,
  `metadesc` text,
  `metadata` text,
  `nowebsr` tinyint(1) NOT NULL DEFAULT '0',
  `featured` tinyint(3) NOT NULL DEFAULT '0',
  `language` char(7) NOT NULL DEFAULT '*',
  `publish_up` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `publish_down` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
    PRIMARY KEY  (`id`),
  KEY `idx_access` (`access`),
  KEY `idx_checkout` (`checked_out`),
  KEY `idx_state` (`published`),
  KEY `idx_catid` (`catid`),
  KEY `idx_createdby` (`created_by`),
  KEY `idx_language` (`language`)
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `#__garyscookbook_comments` (
  `cmtid` int(10) NOT NULL AUTO_INCREMENT,
  `cmtpic` int(10) NOT NULL DEFAULT '0',
  `cmtip` varchar(15)  NOT NULL DEFAULT '',
  `cmtname` varchar(20)  NOT NULL DEFAULT '',
  `cmttext` text  NOT NULL,
  `cmtdate` varchar(20)  DEFAULT NULL,
  `published` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`cmtid`)
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `#__gkb_myrecipes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `userid` int(11) NOT NULL,
  `recipeid` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `userid` (`userid`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 ROW_FORMAT=FIXED;
